### PR TITLE
add comment buttons

### PR DESCRIPTION
**Pull request by JackStrap**
Hi Gourav,

Thanks for making this extension.
I added two buttons for comments, one for toggle comment line and the other one for toggle block comment.
Could you let me know when you published it.

Thanks,
Jack

### CODE REVIEW

**Comment by JerryGoyal** [comment]
Thanks @JackStrap  will check and deploy by the weekend

**Comment by JerryGoyal** [comment]
Hi @JackStrap  I recently updated the extension so the merge process is failing. Could you resolve these conflicts in your PR?

**Comment by JackStrap** [comment]
Hi @JerryGoyal It should be arrange now.
Thanks again!

**Comment by JerryGoyal** [comment]
@JackStrap In the latest PR, there seem to be missing some changes for extension.ts and package.json file. https://github.com/JerryGoyal/Shortcut-Menu-Bar-VSCode-Extension/pull/19/files

**Pull request closed without merging**
