### PR TITLE
add user defined buttons, fixing #28

### PR DESCRIPTION
**Pull request by GitMensch**
* icons made by Freepik https://www.freepik.com (color adjustment and formatting done manually)
* new settings `ShortcutMenuBar.userButton01Command` to `ShortcutMenuBar.userButton10Command`: icons only shown if command is defined; with included keyboard bindings [CTRL]+[ALT]+1,2...,9,0
* command execution (including sequences and parameters) and resolve of variables based on https://github.com/ppatotski/vscode-commandbar

### CODE REVIEW

**Comment by GitMensch** [comment]
Works quite well for me, including command arguments and Parts that _could_ be added later:

* config caching: (all) settings are currently read on command execution and the one that is relevant is then used - one could define an object array for each of the ten buttons and store the commands in there; then create the objects on startup and only if the extension is called because of the configuration changed setup the content again
* additionally store boolean attributes for "active yes/no": "is setup" and from an additional parse of the content "needs active workspace", "needs active Editor" and use this for showing/execute + hide
* automated tests (not sure how those would have to be setup)

I may would work on the first two items later, but I'd prefer a release beforehand.

**Comment by GorvGoyl** [comment]
Thank you. I'll sit this weekend to thoroughly review and test this PR. I noticed that you used custom svg icons for user-defined commands. Could vscode built-in icons be used for this? that way users will have wide varieties of icons to choose from. https://code.visualstudio.com/api/references/icons-in-labels

**Comment by GitMensch** [comment]
> Could vscode built-in icons be used for this?

That's what I would have preferred in the first place...
I know those icons can be used in different places and according to intellisense they can also be used in the command icons - but so far thie command icons are completely hard-wired in package.json, not sure if/how this can be adjusted via extension settings (we'd need a default in any case).

**Comment by GorvGoyl** [comment]
Just tested and it seems to be working fine. Kudos to the numbered icons and its corresponding hotkeys. Amazing work!!

**Comment by GitMensch** [comment]
> Kudos to the numbered icons and its corresponding hotkeys. Amazing work!!

Thanks! Actually that was my second real work with TS, so that's encouraging for going on.

I guess #28 can now be closed and, possibly together with tackling #36, a new version be tagged and released?

**Comment by GitMensch** [comment]
Hm, strangely this PR is not linked to the issue, can you manually do this (in the upper right corner), please?

**Comment by GorvGoyl** [comment]
Will release new version this week on both marketplaces.

**Pull request merged**
